---

name: CI

on: push

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test

  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

  Deploy_Github_Pages:
    name: Deploy (Github Pages)
    runs-on: ubuntu-latest
    needs:
      - Lint
      - Test
      - Build

    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Setup Hosting
        run: |
          touch docs/.nojekyll &&
          echo "pop-vue.origin76.com" > docs/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs

  Deploy_Package:
    name: Deploy (NPM Package)
    runs-on: ubuntu-latest
    needs:
      - Lint
      - Test
      - Build

    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy
        run: npm run release
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_KEY }}
          NPM_TOKEN: ${{ secrets.NPM_KEY }}
